sonar.projectKey=saidicdosonarfrontend
sonar.projectName=SAI Dicdo Frontend
sonar.projectVersion=1.0
sonar.sources=css,js,pages,pdf
sonar.exclusions=images/**,node_modules/**,dist/**,build/**
sonar.host.url=http://localhost:9000
sonar.login=sqp_4884061b5042628a928e1e370a963213851a1dd7


