sonar.projectKey=saidocdobackend
sonar.projectName=SAI Dicdo Backend
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,build/**,*.log,**/*.sql
sonar.host.url=http://localhost:9000
sonar.login=sqp_0790d81c1df0e859baa0684d1e21fd4afbcc8b0e
